puts "Create '69 Chevy Corvette"
Product.find_or_create_by_name :name => "1969 Chevy Corvette", :price => 3, :image_file => "/images/69_corvette.png"
puts "Create '07 Ford Mustang"
Product.find_or_create_by_name :name => "2007 Ford Mustang", :price => 4, :image_file => "/images/07_ford_mustang.png"
puts "Create '67 Ford Mustang"
Product.find_or_create_by_name :name => "1967 Ford Mustang", :price => 5, :image_file => "/images/67_ford_mustang.png"
puts "Create Ferrari Berlinetta"
Product.find_or_create_by_name :name => "Ferrari Berlinetta", :price => 5, :image_file => "images/ferrari_berlinetta.png"
puts "Done!"